### ISSUE TITLE
一个看起来貌似像是有问题的地方 -w-

### ISSUE THREAD

**Issue by daquexian** [fallenwood/minilan-interpreter#1]
乃在 [这一句](https://github.com/fallenwood/minilan-interpreter/blob/master/term.cpp#L608) 之后是不是也应该像 [这一句](https://github.com/fallenwood/minilan-interpreter/blob/master/term.cpp#L593) 一样把 `returned` 更新一下

**Comment by fallenwood** [comment]
fixed
